### ISSUE TITLE
Rails 4 causes problem with missing method

### ISSUE THREAD

**Issue by hubrix** [TwP/logging-rails#13]
/usr/local/Cellar/ruby/1.9.3-p194/lib/ruby/gems/1.9.1/gems/railties-4.0.0/lib/rails/commands/server.rb:78:in `start': undefined method `formatter' for <Logging::Logger:0x3fdcc4e56bf0 name="Rails">:Logging::Logger (NoMethodError)
	from /usr/local/Cellar/ruby/1.9.3-p194/lib/ruby/gems/1.9.1/gems/railties-4.0.0/lib/rails/commands.rb:78:in `block in <top (required)>'
	from /usr/local/Cellar/ruby/1.9.3-p194/lib/ruby/gems/1.9.1/gems/railties-4.0.0/lib/rails/commands.rb:73:in `tap'
	from /usr/local/Cellar/ruby/1.9.3-p194/lib/ruby/gems/1.9.1/gems/railties-4.0.0/lib/rails/commands.rb:73:in `<top (required)>'

**Comment by TwP** [comment]
This is solved by upgrading Logging to 1.8.2
